name: not-lb
grade: stable
version: 0.0.1
summary: The best place to store and share thoughts
description: |
  Privacy shouldn't be a compromise. That's why we made Lockbook, a companion
  for recording thoughts on all your devices. Record, sync, and share your
  notes with apps engineered to feel like home on every platform. We collect no
  personal information and encrypt your notes so even we can't see them. Don't
  take our word for it: Lockbook is 100% open-source.

architectures:
  - build-on: amd64
    run-on: amd64

base: core20
confinement: strict

apps:
  not-lb:
    command: bin/lockbook
    plugs: [network]

  gui:
    command: bin/lockbook-gui
    extensions: [gnome-3-38]
    plugs: [network]


parts:
  build-all:
    plugin: nil
    source: https://github.com/lockbook/lockbook.git
    source-subdir: clients/cli
    build-packages:
      - libgtksourceview-3.0-dev

    stage-packages:
      - libgtksourceview-3.0-1

    override-build: |
      if ! command -v rustup 2> /dev/null; then
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path --profile=minimal
          export PATH="${HOME}/.cargo/bin:${PATH}"
      fi

      cargo install --force --locked --path clients/linux --root "${SNAPCRAFT_PART_INSTALL}"
      mv "${SNAPCRAFT_PART_INSTALL}/bin/lockbook" "${SNAPCRAFT_PART_INSTALL}/bin/lockbook-gui"

      cargo install --force --locked --path clients/cli --root "${SNAPCRAFT_PART_INSTALL}"
